#!/usr/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

VERSION=`curl  "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c2-` 
wget https://github.com/cli/cli/releases/download/v${VERSION}/gh_${VERSION}_linux_amd64.tar.gz -O /tmp/gh_${VERSION}_linux_amd64.tar.gz
tar -xf /tmp/gh_${VERSION}_linux_amd64.tar.gz -C /tmp
cp /tmp/gh_${VERSION}_linux_amd64/bin/gh /usr/local/bin/
cp -r /tmp/gh_${VERSION}_linux_amd64/share/man/man1/* /usr/share/man/man1/
rm -rf /tmp/gh_${VERSION}_linux_amd64/
